### ISSUE TITLE
error by serial.enable()

### ISSUE THREAD

**Issue by mkolja** [OpenMote/firmware#1]
I get an error by serial.enable(). I guess it should be changed to seria.init() ?

**Comment by peretuset** [comment]
In which project does the error appear?

**Comment by mkolja** [comment]
sorry, I thought it will be visible, since I reported it from the project already. It is in test-radio project.

**Comment by peretuset** [comment]
You are right, it should be init instead of enable. The issue was not caught by the CI framework due to the define directive. I have pushed a commit that fixes the issue. Thanks!
